version: "3"
services:
  web_app:
    container_name: weather_station_api
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${APP_DB_DATA_PATH}:/WeatherStationAPI/data
    env_file:
      - .env